name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node.js 환경 설정
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 의존성 설치
      - run: npm ci

      # 빌드 (React라면)
      - run: npm run build

      # Firebase deploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEDDING_INVITATION_33CF3 }}
          channelId: live
          projectId: wedding-invitation-33cf3
